#!/bin/bash

zlicz_pliki() {
    if [ $# -ne 1 ]; then
        echo "Blad: Oczekiwano 1 argumentu" >&2
        return 1
    fi
    
    if [ ! -d "$1" ]; then
        echo "Blad: Katalog nie istnieje" >&2
        return 1
    fi
    
    liczba=$(find "$1" -maxdepth 1 -type f | wc -l | tr -d ' ')
    
    echo "Katalog zawiera $liczba plikow"
}

zlicz_pliki "$@"
