#!/bin/bash

producer_consumer() {
    if [ $# -ne 2 ]; then
        echo "Blad: Oczekiwano 2 argumentow" >&2
        return 1
    fi
    
    if ! [[ "$1" =~ ^[0-9]+$ ]] || [ "$1" -le 0 ] || ! [[ "$2" =~ ^[0-9]+$ ]] || [ "$2" -le 0 ]; then
        echo "Blad: Argumenty musza byc liczbami dodatnimi" >&2
        return 1
    fi
    
    if [ "$2" -gt "$1" ]; then
        echo "Blad: Okno nie moze byc wieksze niz liczba iteracji" >&2
        return 1
    fi
    
    iteracje="$1"
    okno="$2"
    potok="/tmp/potok_$$"
    
    mkfifo "$potok"
    
    (
        for ((i=0; i<iteracje; i++)); do
            liczba=$((RANDOM % 101))
            echo "$liczba"
        done
    ) > "$potok" &
    
    producer_pid=$!
    
    (
        declare -a bufor
        indeks=0
        
        while read liczba; do
            bufor[$indeks]=$liczba
            indeks=$((indeks + 1))
            
            if [ $indeks -le $okno ]; then
                ilosc=$indeks
            else
                ilosc=$okno
            fi
            
            suma=0
            start=$((indeks - ilosc))
            for ((j=start; j<indeks; j++)); do
                suma=$((suma + bufor[j]))
            done
            
            srednia=$(echo "scale=2; $suma / $ilosc" | bc)
            echo "Liczba: $liczba Srednia: $srednia"
        done < "$potok"
    ) &
    
    consumer_pid=$!
    
    wait $producer_pid
    wait $consumer_pid
    
    rm -f "$potok"
}

producer_consumer "$@"

